# Generated by Django 2.1.5 on 2019-02-09 02:18

from django.db import migrations, models
import img_uploader.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(height_field='img_height', upload_to=img_uploader.models.md5_filename, width_field='img_width')),
                ('img_width', models.PositiveIntegerField(default=1)),
                ('img_height', models.PositiveIntegerField(default=1)),
                ('md5hex', models.CharField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('new_date', models.DateTimeField(verbose_name='upload date')),
            ],
        ),
    ]
